apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: s3-upload-sa-binding
subjects:
- kind: ServiceAccount
  name: s3-upload-sa
  namespace: s3-upload
roleRef:
  kind: ClusterRole
  name: s3-upload-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: db-secret-sa-binding
subjects:
- kind: ServiceAccount
  name: db-secret-sa
  namespace: jom
roleRef:
  kind: ClusterRole
  name: {{ .Values.env }}-db-secret-access-role
  apiGroup: rbac.authorization.k8s.io