apiVersion: apps/v1
kind: Deployment
metadata:
  name: jom-be
  namespace: jom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jom-be
  template:
    metadata:
      labels:
        app: jom-be
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.awsAccountID }}:role/{{ .Values.env }}-db-secret-access-role"
    spec:
      containers:
      - name: jom-be
        image: "{{ .Values.awsAccountID }}.dkr.ecr.{{ .Values.awsRegion }}.amazonaws.com/{{ .Values.env }}-jom-be:{{ .Values.imageTag }}"
        ports:
        - containerPort: 8000
        env:
        - name: "AWS_SECRET_NAME"
          value: "{{ .Values.env }}{{ .Values.db }}/root"
      serviceAccountName: db-secret-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jom-fe
  namespace: jom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jom-fe
  template:
    metadata:
      labels:
        app: jom-fe
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.awsAccountID }}:role/{{ .Values.env }}-ecs-upload-role"
    spec:
      containers:
      - name: jom-fe
        image: "{{ .Values.awsAccountID }}.dkr.ecr.{{ .Values.awsRegion }}.amazonaws.com/{{ .Values.env }}-jom-fe:{{ .Values.imageTag }}"
        ports:
        - containerPort: 3000
        env:
        - name: "JOM_BE_ADDRESS"
          valueFrom:
            configMapKeyRef:
              name: jom-be-config
              key: JOM_BE_ADDRESS
        - name: "STATIC_BUCKET_ADDRESS"
          valueFrom:
            configMapKeyRef:
              name: jom-fe-config
              key: STATIC_BUCKET_ADDRESS
      serviceAccountName: s3-upload-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: jom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
