apiVersion: v1
kind: Service
metadata:
  name: jom-fe-svc
  namespace: jom
spec:
  selector:
    app: jom-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jom-be-svc
  namespace: jom
spec:
  selector:
    app: jom-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: jom
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
