apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-upload-sa
  namespace: jom
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsAccountID }}:role/{{ .Values.env }}-eks-pod-upload-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-secret-sa
  namespace: jom
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsAccountID }}:role/{{ .Values.env }}-db-secret-access-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jom-batch-sa
  namespace: jom